---
title: "Black bear hunting activity and harvests - Open Ontario"
author: "Dean Jayatilleke & Junpu Xie & Dave Campbell"
date: '2020-08-10'
slug: wild-life-data-balck-bear-hunting-activity-and-harvests-data-catalogue-from-goverrnment-of-ontario
categories: ["Regression"]
tags: ["Linear Chart", "Linear Regression", "Time Series", "Wildlife Data", "Ontario"]
subtitle: ''
summary: 'The dataset records numbers of black bears harvested and active black bear license holders every year from 2012 to 2018 in different wildlife management unit (WMU).'
output: html_document
---

## Possible Analysis and Keywords

- Linear Chart
- Simple Linear Regression
- Time Series
- Hunting Bears
- Wildlife Data
- Ontario Open Data

## Data Provider

The provincial government of Ontaio provides open access to thousands of data sets via their [Open Data Ontario](https://data.ontario.ca/en/) portal. The purpose of sharing all data documents with the public is to remain transparent and accessible.  More details about the data license, training materials, and other information can be found [here](https://data.ontario.ca/about).

***

## Black Bear Hunting Activity

The dataset records numbers of black bears harvested and active black bear license holders every year from 2012 to 2018 in different wildlife management unit (WMU). The WMUs are the administrative coverage area that serves as a land base for wildlife monitoring and management.  

The original dataset of bear harvested and active hunters and its supporting document can be found [here](https://data.ontario.ca/en/dataset/black-bear-hunting-activity-and-harvests) and you can quickly preview the CSV dataset file [here](https://data.ontario.ca/en/dataset/black-bear-hunting-activity-and-harvests/resource/7dd6328e-74cc-4291-a041-2345cf7c6186). Moreover, The legend description can be viewed [here](https://files.ontario.ca/data-dictionary-black-bear-en.xlsx).





## Exploratory Analysis

### Organizing Dataset

The following code is used to download and change the data format of the year.

```{python dataset}

import pandas as pd 
import seaborn as sb

# Download the csv file AND change the data format of the year
data_download = pd.read_csv("https://files.ontario.ca/opendata/black_bear_2019.csv")

data_download.head()

total = data_download[data_download.WMU == "Total"]
data = data_download[data_download.WMU != "Total"]

```

The data has columns WMU, year, number of active hunters, and the harvest.  All numbers of bear harvested and active hunters are estimated based on the replies received from a sample of hunters, so it might contain a statistical error.  In the WMU called Total, all of the WMUs are summed.

```{python}
total.head()
data.head()
```

### Plotting the Number of Bear Hunters and Harvest

The following code plots the number of bears harvested per active hunter in each WMU.






```{python plots}

sb.scatterplot(data=data, x='Active Hunters', y='Harvest', hue='WMU', legend=False).set_title("Hunters and Harvest in different WMUs")


```


