---
title: 'Cansim Library for Socio-Economic data'
author: "Dave Campbell"
date: '2021-06-11'
slug: socioeconomic-time-series-and-statistics-canada
categories: ["Census Data"]
tags: ["Linear Regression", "Time Series",  "Official Statistics", "Census Data"]
subtitle: ''
summary: 'Using R libraries to acquire socioeconomic data from Statistics Canada Mapper.'
lastmod: '2021-06-11T18:40:19-04:00'
---
  
# Possible Analysis and Keywords

- Regular Expressions
- String Manipulation
- Merging Datasets
- Socioeconomic Data
- Canadian Data
- Regression
- Housing



# Goals

First we pull socioeconomic data from Statistics Canada.  We manipulate and plot the unemployment rates.  Then we pull housing starts and consider relationships between the two datasets.


# Data Provider

[cansim](https://cran.r-project.org/web/packages/cansim/vignettes/cansim.html) makes it easy to pull Statistics Canada's table datasets.  

For larger tables, **cansim** offers sqlite integration.  See for example the [vignette](https://cran.r-project.org/web/packages/cansim/vignettes/working_with_large_tables.html)





***


# Installing cansim
  
  There are a lot of specifics in the package vignette, one way to view them is to install the library and use the **vignette* function:
  
```{R cancensus package, eval=FALSE}

install.packages("cansim")
library(cansim)
vignette("cansim")

#code not run for this document.
```
  
  
# Basic libraries 

```{R, message = FALSE, warning = FALSE}
library(tidyverse) # for its nice flow.
library(cansim) #for pulling Stat Can socioeconomic data
library(lubridate) # for dealing with dates
library(GGally) # for pairs plot
library(ggpubr) # for putting a regression equation onto a ggplot figure
````
  
  
## Pulling a table

Visit [here](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701&pickMembers%5B0%5D=1.1&pickMembers%5B1%5D=3.1&pickMembers%5B2%5D=4.1&pickMembers%5B3%5D=5.1&cubeTimeFrame.startMonth=01&cubeTimeFrame.startYear=1976&cubeTimeFrame.endMonth=01&cubeTimeFrame.endYear=2021&referencePeriods=19760101%2C20210101) for example to see labor force data in html.
Notice that the StatCan webpage shows the table id, here it is table: 14-10-0287-01.

We'll use that to grab the table.   Be warned that this data table is a csv of around 1 GB in size.  While we're at it, let's remake some column names to make them more R friendly.  


```{R, message = FALSE, cache = TRUE, warning = FALSE}
data = get_cansim("14-10-0287-01") %>% rename_all(make.names) 

data %>% glimpse

```

There are nearly 5 million rows of data!  


## Make a few plots of Employment statistics


Stat Can tables are structured so that each row has a single value and columns define attributes about that value  Each row of data has a specific attribute sex, age (**Age.group**), and Location (**GEO**) attributes, for units of the value (**SCALAR_FACTOR**), the specific type of labour force characteristic measured (**Labour.force.characteristics**), and the differences data types such as point estimates and (bootstrap) standard errors (**Statistics**), and raw or seasonally adjusted (**Data.type**).  In general this means that we need to filter and reshape the data.  

Let's inventory a few of these columns so that the exact spelling of attributes can be used below in the plots.
```{R}
data$Labour.force.characteristics  %>% unique()
data$Statistics  %>% unique()
data$Age.group  %>% unique()
data$GEO  %>% unique()
```

### Plotting provinces against each other
Let's consider provincial differences in employment rate for 25-55 year olds.  Using the spelling from the above output we can set up the data filters.


##### When **pivot_wider** Works, But Not As Intended; Common Errors and How to Fix Them
Pivoting a data table will spread out a variable into new columns.  Sometimes it's more convenient to have each province as it's own column.  Here we do this to plot provinces against each other and see how they relate.  It  can be helpful to see how to accidentally break things, so let's start there.  
I will need to filter the data so let's start there.  Here we go right from selecting columns, filtering and then pivoting wider, which will help when plotting.  Take a look at the output.


```{R, employmentProvinces0}

data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  pivot_wider(names_from= GEO, values_from=VALUE) %>%  # puts each province into its own column
  rename_all(make.names) # rebuilt the province names

```

The provinces are now _list_ variables, whereas they should be _doubles_ (single numbers).  It wasn't obvious to me what went wrong the first time I broke a pivot table like this.  Let's re-run those steps without the **pivot_wider** and see if it helps to diagnose the root of the problem.  This is one of the great parts of tidyverse, we just rerun a subset of the above code, or explicitely extract one of those list elements from the original call:

```{R, employmentProvinces1}
# run fewer lines of the previous code:
data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")


## or view the problem this way, select Ontario and check out the first element:
# data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE)%>%
#   filter(Sex == "Both sexes") %>% 
#   filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
#   filter( Labour.force.characteristics == "Unemployment rate")%>%
#   filter(Age.group == "25 to 54 years")%>%
#   pivot_wider(names_from= GEO, values_from=VALUE) %>%  # puts each province into its own column
#   rename_all(make.names) %>% 
#   select(Ontario)%>% head%>% .[[1]]


```
If you look closely at the output in the first strategy you'll notice that there are multiple rows which only differ in their **VALUE**. This means that **pivot_wider** is mapping multiple rows of **VALUE** into a single element.  R handles this by smashing all those values together into list elements.  

In order to have a one-to-one mapping add another variable to create a unique mapping.  Taking another close look at the **glimpse** output above, we can see that there is more than one **Data.type**.  Checking out its values we see the following:

```{R}
data$Data.type  %>% unique()
```

The multiple **VALUE**s are made unique when considering the **Data.type** variable.  To simplify things, let's select the _Unadjusted_ unemployment rate.

##### When **pivot_wider** Works As Intended

```{R, employmentProvinces1.5}

data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE,Data.type)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  filter(Data.type == "Unadjusted")%>%
  pivot_wider(names_from= GEO, values_from=VALUE) %>%  # puts each province into its own column
  rename_all(make.names) 

```

### Plotting Variables Against Each Other.

```{R, employmentProvinces2}

data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE,Data.type)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  filter(Data.type == "Unadjusted")%>%
  pivot_wider(names_from= GEO, values_from=VALUE) %>%  # puts each province into its own column
  rename_all(make.names) %>% 
ggpairs( columns = 6:15, title = "Monthly Unemployment Rate: Not Seasonaly Adjusted",  
        axisLabels = "show")


```





### Plotting the Provinces as Time Series

We won't bother pivoting the data table anymore, since it's convenient for **ggplot** to have a column as an identifying feature.

Notice that the **REF_DATE** column is a character but it should be a date.  We'll use the lubridate package for converting into dates.  The helpfile for the _parse_date_time_ function is really useful for specifying the input format, as it clarifies that **Y** is a year with century but **y** is the two digit year without century.  Using the wrong one will break the mutation.


```{R, employmentProvinces3}
data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE,Data.type)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  filter(Data.type == "Unadjusted")%>%
  mutate(date = parse_date_time(REF_DATE, orders = "Y-m"))%>% # convert from character date to date format.
  rename(unemployment.rate = VALUE)%>%
  ggplot(aes(x=date, y = unemployment.rate, colour = GEO))+
  geom_line()+
  ggtitle("Unemployment Rates by Province")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+# rotate axis labels so they don't overlap
  facet_wrap(~GEO)

```



## Plot the Within Year Seasonal Trends


Let's split the date into year and month columns using the **separate** function.
Then within a provincial facet we can plot each year as a different line.  This figure makes lines darker as they go through the years by using **year** as the colour variable but highlights 2020-2021 in red using a second call to the _geom_line_ function. There are a few strategies to do this, here I built a dataset with a new mutated variable specifying the 2020-2021 years and used it for plotting.  This begins with a lot of filtering to obtain the 'right' data.

In some provinces, the strong seasonality of the unemployment rate realy pops out.  

```{R, employmentProvinces4}

data4plot = data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE,Data.type)%>%
  filter(Sex == "Both sexes") %>% 
  filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  filter(Data.type == "Unadjusted")%>%
  separate(REF_DATE, into = c("year","month"),sep = "-")%>%#split year-month into year  month columns
  mutate(year = as.numeric(year))%>%
  mutate(month = as.numeric(month))%>%
  rename(unemployment.rate = VALUE)

  ggplot()+
  geom_line(data=data4plot,aes(x=month, y = unemployment.rate, colour = year, group = year))+
  # re-add in the pandemic year wwhile forcing the colour red
  geom_line(data=data4plot%>% filter(year>2019),aes(x=month, y = unemployment.rate, group = year),colour = "red",lwd=1.24)+
    #add to the manual legend.
  scale_x_continuous(breaks = c(2,4,6,8,10))+
  ggtitle("Unadjusted Unemployment Rates by Province for 25 - 54 Year Olds: highlighting pandemic years")+
  facet_wrap(~GEO)
```




## Plot the within year seasonal trends, but highlihght by decade

 This figure uses a mutated variable defining the decade to set line colours,  so 2020-2021 are inherrently already highlighted.
 
This time the Canadian average is included, despite the fact that it is a weighted average of the provincial values.  __Note that this time we are also keeping the filtered, mutated data to simplify merging datasets later.__

```{R, pandemic5}

unemployment = data %>% select(GEO,Sex,Age.group,Labour.force.characteristics,REF_DATE,VALUE,Data.type)%>%
  filter(Sex == "Both sexes") %>% 
  # filter(GEO != "Canada")%>% # since the Canada value will be a type of weighted average
  filter( Labour.force.characteristics == "Unemployment rate")%>%
  filter(Age.group == "25 to 54 years")%>%
  filter(Data.type == "Unadjusted")%>%
  separate(REF_DATE, into = c("year","month"),sep = "-")%>%#split year-month into year  month columns
  mutate(year = as.numeric(year))%>%
  mutate(month = as.numeric(month))%>%
  mutate(pandemic = 1+.1*as.numeric(as.numeric(year>=2020)))%>%
  mutate(decade = factor(floor(year/10)*10 ))%>%
  rename(unemployment.rate = VALUE)%>%
  rename(province = GEO)
  


  ggplot(data = unemployment)+
  geom_line(aes(x=month, y = unemployment.rate, colour = decade, group = year))+
  scale_colour_brewer(palette = "Paired")+ # nicer colours
  scale_x_continuous(breaks = c(2,4,6,8,10))+ # place axis labels on even numbered months
  ggtitle("Unemployment Rates by Province")+
  facet_wrap(~province)

```



## Housing starts


The housing starts are more complicated beacuse they are based on cities but the unemployment is based on provices

```{R, housing, cache = TRUE}
housing = get_cansim("34-10-0154-01") %>% rename_all(make.names) 

housing %>% glimpse
# the unique cities
housing %>% pull(GEO) %>% unique
```


To merge the housing starts with the unemployment, we need to set both to the same measurement unit, provinces per {month, year}.  To construct provincial housing starts, sum over the municipailites within a province. Many of these StatCan tables have multiple data types, so we will only consider **Housing.estimates** = _"Housing starts"_ and **Type.of.unit ** = _"Total units"_.

Notice that Ottawa-Gatineau is split into ON and QC parts.


Let's use the separate function to split apart the province and city.  Considering the **GEO** location **"Ottawa-Gatineau, Ontario part, Ontario/Quebec"** and splitting at the "," we can end up with some innaccurate provinces **"Ontario/Quebec"** or destroy the useful location information by removing **"Ontario part"**.

Here are a few options using regular expressions.  Note that most of these give warnings, generally complaining about the **GEO** location  _"Census metropolitan areas"_.  Strategies to split the **GEO** location at commas will result in NA's since this location has no comma.  Those warnings are left in the output below.

```{R}
# set up city by replacing everything after the first "," with "":
housing %>% mutate(city = str_replace_all(GEO, pattern = "(,\\s).*", replacement ="")) %>% 
  pull(city) %>% unique %>% head(16)

#Split everything at the last comma:
# Separate GEO at a ", ", but if more than one exists find the one which is NOT followed by any characters, then a comma:
#Notice how this handles the Ontario and Quebec parts of the Ottawa-Gatineau region
housing %>% separate(GEO, into  = c("city","province"), sep = ",\\s(?!(.*,))") %>% 
  select(city,  province) %>%
  unique%>% head(16)

#Build the province by splitting at the first comma, then adjusting the province by 
# handing cases such as "Ontario part, Ontario/Quebec"
# notice that I'm actually splitting at all commas and allowing anything after the 
# second comma (where it exists) to be discarded.
housing %>% separate(GEO, into  = c("city","province"), sep = ",\\s") %>% 
  mutate(province = str_replace_all(province, pattern = " part", replacement = ""))%>%
  select(city,  province)%>% unique%>% head(16) 
#note that this leaves in an artifact province :"Ontario/Quebec" from Ottawa-Gatineau 
# but that is a combo of the Ontario part and the Quebec part
# that province combo could be replaced with NA and then eliminated later
# for example:

housing %>% separate(GEO, into  = c("city","province"), sep = ",\\s") %>% 
  mutate(province = str_replace_all(province, pattern = " part", replacement = ""))%>%
  mutate(province = str_replace_all(province, pattern = "Ontario/Quebec", replacement = "NA"))%>%
  select(city,  province)%>% unique%>% head(16) 
```

#### Preparing for Merging Datasets

Here we rebuild the dataset and sum housing starts within provinces to obtain 

```{R}
# We will keep the final strategy above, but also mutate in the
# Housing.estimates  and Type.of.unit
# select fewer variables, to clean it up prior to merging datasets
housing.starts = housing %>% separate(GEO, into  = c("city","province"), sep = ",\\s") %>% 
  mutate(province = str_replace_all(province, pattern = " part", replacement = ""))%>%
  mutate(province = str_replace_all(province, pattern = "Ontario/Quebec", replacement = "NA"))%>%
  rename(housing.starts = VALUE)%>% # so I'm not confused later
  filter(Housing.estimates == "Housing starts")%>%
  filter(Type.of.unit == "Total units") %>%
  filter(!is.na(province))%>% # get rid of census metropolitan areas
  mutate(date = parse_date_time(REF_DATE, orders = "Y-m"))%>% # convert from character date to date format.
  separate(REF_DATE, into = c("year","month"),sep = "-")%>%#split year-month into year  month columns
  mutate(year = as.numeric(year))%>%
  mutate(month = as.numeric(month))%>%
  group_by(province, year, month, date) %>% # look within provinces at a given time
  summarize(total.housing = sum(housing.starts)) %>%
  ungroup() 




housing.starts %>% glimpse
```

#### Clean up extraneous columns, and merge datasets:

By default _inner_join_ will merge two datasets based on their common column names. Only rows which appear in both datasets will be kept.

```{R}

both =  unemployment %>%
  select(province, year, month, decade,pandemic, unemployment.rate) %>% 
  inner_join(housing.starts)


both %>% glimpse
```


#### Comparing Unemployment and Housing Starts

Note that there are Prince Edward Island and the territories not represented within the housing starts dataset and therefore are not in the following plots.

In general as unemployment increases, housing starts decrease.


```{R}

both %>% ggplot(aes(x=unemployment.rate, y =total.housing))+
  geom_point( aes(colour =  province, group = province),alpha = .1)+#alpha is the transparancy of the points
  ggpubr::stat_regline_equation()+
  geom_smooth(method = "lm")+
  facet_wrap(~province)


```





#### Going Further

- Make residual plots for the linear regessions
- Consider other variables/ relationship, such as   CPI from table **18-10-0004-01  Consumer Price Index, monthly, not seasonally adjusted**
- Consider looking for a time varying trend, subsetting the years, or even multiple regression with a year effect.

