---
title: "COVID Data: COVID-19 Data - Government of Canada"
author: "Dean Jayatilleke & Junpu Xie & Dave Campbell"
date: '2020-07-24'
slug: covid-data-covid-19-govenrmnent-of-canada-and-jhu-csse
categories: ["COVID Data"]
tags: ["Linear Regression", "Normal Distribution","Time Series", "Aggregated Ddata", "Spatial Data Set", "COVID-19", "COVID Data"]
subtitle: ''
summary: The Government of Canada provides detailed information about COVID-19 data in time-series and aggregated forms, broken down by province.'
lastmod: '2020-07-24T18:48:09-04:00'
ipynb-shell-interactivity: all
---

## Possible Analysis and Keywords
- Linear Regression
- Normal Distribution
- Time Series
- Aggregated Data
- Spatial Data Set
- COVID-19
- COVID Data

## Data Provider - Worldwide 

COVID-19 data plays a vital role in managing a pandemic. Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE), ESRI Living Atlas Team and the Johns Hopkins University Applied Physics Lab (JHU APL) have compiled a COVID-19 data repository which is updated in real-time with worldwide COVID-19 [data](https://github.com/CSSEGISandData/COVID-19).

The real-time visual dashboard can be viewed in [desktop](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) and [mobile](http://www.arcgis.com/apps/opsdashboard/index.html#/85320e2ea5424dfaaa75ae62e5c06e61).

## Data Provider - Canada

COVID-19 is a serious health threat for individuals and its extended social problems are also evolving daily. Based on the given number of cases in Canada, the risk to Canadians is still considered high. 

The government of Canada updates regular COVID-19 information and news [here](https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.html), it also creates interactive data visualizations by providing a visual data gallery [here](https://health-infobase.canada.ca/covid-19/visual-data-gallery/), so that everyone can easily see the current situation of COVID-19 across Canada and the world with different measurements. Health Canada provides several visualizations including the [Canada COVID-19 Situational Awareness Dashboard](https://experience.arcgis.com/experience/2f1a13ca0b29422f9b34660f0b705043/?fbclid=IwAR0k_pf1jxwanqldeaZy0-1bao8njVXrz6A3-ejp72Kyh4Qcj0MrE72lgdo) and [interactive data map](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html).

***

## COVID-19 Data from the Government of Canada

The COVID-19 data from the Government of Canada provide detailed information in number, percent, and rate data of tested, confirmed, recovered, and death cases in time series, it is also aggregated forms with a given date among different provinces and you can view and download the dataset [here](https://health-infobase.canada.ca/src/data/covidLive/covid19.csv).

### Organizing Data

 
```{python packages}

import pandas as pd # data cleaning and organizing
import seaborn as sb # plotting
import matplotlib.pyplot as plt # plot management

```

The following code is used to download and reorganize the original dataset from webpage.

The data is collected chronologically so we take a look at the end of the data to see what variables are still being updated.

```{python dataset}

canadian_data = pd.read_csv("https://health-infobase.canada.ca/src/data/covidLive/covid19.csv")

canadian_data["date"] = pd.to_datetime(canadian_data["date"], 
                                       dayfirst = True)
canadian_data.tail()
```

### Total COVID-19 Cases

Let's start by looking at total cases.

```{python totalcases}

sb.set_style("darkgrid")

canada_total = sb.lineplot(data = canadian_data[(canadian_data["prname"] == "Canada")],
                           x = "date",
                           y = "totalcases")

plt.title("Total Covid-19 Case Count in Canada")
plt.xlabel("Date")
plt.ylabel("Total Cases")
plt.show()

plt.clf()
provinces_total = sb.lineplot(data = canadian_data[(canadian_data["prname"] != "Canada") &
                                                   (canadian_data["prname"] != "Repatriated travellers")],
                              x = "date",
                              y = "totalcases",
                              hue = "prname")

plt.title("Total Covid-19 Case Count by Province")
plt.xlabel("Date")
plt.ylabel("Total Cases")
plt.legend(title = "Province",
           bbox_to_anchor=(1.05, 1),
           loc='upper left',
           borderaxespad=0)
plt.show();

```


Looking at the case count broken down by province we can see that the Canadian trend is largely driven by Ontario and Quebec. This is to be expected as these provinces account for over half the population of the country.  

### Seasonal Trends

Total cases can be expected to increase indefinitely but of more interest is how Covid-19 will settle into a yearly pattern, much like the seasonal cold and flu.

```{python canada yearly trends}

plt.clf()

sb.lineplot(data = canadian_data[(canadian_data["prname"] == "Canada")],
            x = "date",
            y = "numdeaths_last7")

plt.title("Covid-19 Deaths by Week in Canada")
plt.xlabel("Date")
plt.ylabel("Covid-19 Deaths in Last 7 Days")

plt.show();

```

As predicted, Covid-19 deaths appear to follow a yearly pattern peaking during cold and flu season. 2023 and 2024 observed a large drop off Covid-19 deaths, possibly due to higher vaccination rates and increased awareness. 

```{python provincial yearly trends}

plt.clf()

sb.lineplot(data = canadian_data[(canadian_data["prname"] != "Canada") &
                                 (canadian_data["prname"] != "Repatriated travellers")],
            x = "date",
            y = "numdeaths_last7",
            hue = "prname")

plt.title("Covid-19 Deaths by Week in Provinces")
plt.xlabel("Date")
plt.ylabel("Covid-19 Deaths in Last 7 Days")

plt.legend(title = "Province",
           bbox_to_anchor=(1.05, 1),
           loc='upper left',
           borderaxespad=0)

plt.show();

```

As with the total case count, the Canada wide trend seems to be driven by the Ontario and Quebec seasonal trends. 


